blog/src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert ;
// https://symfony.com/doc/current/validation.html
// vérification au niveau du formulaire 
// vérifier au moment de l'insertion 


#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 200 , nullable:true)]
    #[Assert\Length(
            min:2, 
            max:200 , 
            minMessage : "le titre doit contenir au minimum {{ limit }} lettres",
            maxMessage : "le titre doit contenu au mximum {{ limit }} lettres"
            )]
    private $titre;
    
    /**
     * @var string
     */
    #[ORM\Column(type: 'text')]
    #[Assert\Length(
        min:2 ,
        max:2000 ,
        minMessage:"le champ contenu doit contenir {{ limit }} lettres, vous avez saisi {{ value }} caractères",
        maxMessage:"le champ contenu doit contenir {{ limit }} lettres, vous avez saisi {{ value }} caractères",
        //normalizer:fn($contenu) => trim($contenu),
    )]
    private $contenu;

    #[ORM\Column(type: 'boolean')]
    private $publie;

    #[ORM\Column(type: 'datetime')]
    private $dt_creation;

    public function trim(string $contenu) : string{
        return trim($contenu) ; // permet d'enlever les espaces en début et fin d'une string
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function isPublie(): ?bool
    {
        return $this->publie;
    }

    public function setPublie(bool $publie): self
    {
        $this->publie = $publie;

        return $this;
    }

    public function getDtCreation(): ?\DateTimeInterface
    {
        return $this->dt_creation;
    }

    public function setDtCreation(\DateTimeInterface $dt_creation): self
    {
        $this->dt_creation = $dt_creation;

        return $this;
    }
}

blog/src/Controller/HomeController.php
<?php 

namespace App\Controller ;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController{

    #[Route("/" , name:"home_accueil")]
    public function home( ArticleRepository $article ):Response{
        $articles = $article->findAll();
        return $this->render("home/index.html.twig", [ "articles" => $articles ]);
    }

    #[Route("/new" , name:"home_new")]
    public function new(): Response{
        return $this->render("home/new.html.twig");
    }

    #[Route("/new-form", name:"home_new_form")]
    public function new_form(Request $request , ManagerRegistry $doctrine) :Response {
        // $_POST 
        // Request class de Symfony qui contient toutes le super globales 
        // $_POST // $_GET ... 
        //dump($request); 
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article); 
        $form->handleRequest($request); // récupére les valeurs stockées dans le $_POST
        if($form->isSubmitted() && $form->isValid()){
            $article->setDtCreation(new \DateTime()); // remplir le colonne dt_creation avec maintenant
            $em = $doctrine->getManager(); // entity Manager => 
            $em->persist($article); // créer une requête SQL => INSERT
            $em->flush();           // exécuter la requête persistée 
           // dump("l'article est enregistré en base de données"); 

            // INSERT UPDATE => $em->persist()
            // SELECT $article->findAll();
            // DELETE $em->remove()
            $this->addFlash("message" , "l'article est enregistré en base de données");
            return $this->redirectToRoute("home_new_form");
        }
        return $this->render("home/new-form.html.twig", ["form" => $form->createView()]);
    }

    #[Route("/article/update/{id}" , name:"home_modif")]
    public function article_update($id , ManagerRegistry $doctrine , Request $request) : Response{

        // récupérer l'article que l'on veut modifier 
        $article = $doctrine->getManager()->getRepository(Article::class)->find($id);
        // ?? existe
        // si non stop
        //if($article === null){ équivalent
        if(is_null($article)){
            $this->addFlash("erreur", "article numéro $id n'est existe pas");
            return $this->redirectToRoute("home_accueil");
        } 

        $form = $this->createForm(ArticleType::class , $article);

        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em = $doctrine->getManager();
            $em->persist($article);
            $em->flush();
            return $this->redirectToRoute("home_accueil");
        }

        // si oui => appeler une page contenant un formulaire remplir 
        return $this->render("home/new-form.html.twig", ["form" => $form->createView()]);
    }

    #[Route("/article/delete/{id}" , name:"home_suppr")]
    public function article_delete($id, ManagerRegistry $doctrine): Response{
       // récupérer l'article que l'on veut supprimer
       $article = $doctrine->getManager()->getRepository(Article::class)->find($id);
       
       // ?? existe
        // si non stop
        if($article === null){
            $this->addFlash("erreur", "article numéro $id n'est existe pas");
            return $this->redirectToRoute("home_accueil");           
        }

        // si oui => effectuer la suppression
        $this->addFlash("message", "article numéro ". $article->getId() ." vient d'être supprimé");
        $em = $doctrine->getManager();
        $em->remove($article);
        $em->flush();
        return $this->redirectToRoute("home_accueil");
    }
}

blog/templates/home/index.html.twig
{%  extends "front.html.twig" %}

{% block titre %} Accueil {% endblock %}

{% block body %}
<main class="row">
        {% for info in app.flashes("message")%}
            <div class="col-12 alert alert-success my-3">{{ info }}</div>
        {% endfor %}
        {% for article in articles %}
       
        <article class="col-3 border mt-3">
            <div class="my-3">
                <a href="{{ path("home_modif" , { "id" : article.id }) }}" class="btn-info btn" >modifier</a>
                <a href="{{ path("home_suppr" , { "id" : article.id }) }}" class="btn btn-danger">supprimer</a>
            </div>
            <h2>{{ article.titre }}</h2>
            <p>{{ article.contenu }}</p>
            <ul>
                <li> date de création  : {{ article.dtCreation | date("d/m/Y") }}</li>
            </ul>
        </article>
       
    {% endfor %}
</main>
{% endblock %}

blog/templates/home/new-form.html.twig
{% extends "front.html.twig" %}

{% block titre %} formulaire twig {% endblock %}

{% block body %}
    <main class="container">
        {{ form(form) }}
        {% for message in  app.flashes("message") %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
    </main>
{% endblock %}

blog/templates/home/new.html.twig
{%  extends "front.html.twig" %}
{% block titre %} créer un nouvel article {% endblock %}
{% block body %}
<main class="row">
       <h1>créer un nouvel article</h1>
       <form method="POST">
        <div class="mb-3">
            <label for="titre">titre</label>
            <input type="text" id="titre" name="titre" class="form-control">
        </div>
        <div class="mb-3">
            <label for="contenu">contenu</label>
            <textarea name="contenu" id="contenu" cols="30" rows="10" class="form-control"></textarea>
        </div>
        <div class="mb-3 form-check">
            <label for="publie">publie
                <input type="checkbox" id="publie" class="form-check-input">
            </label>
        </div>
        <div class="mb-3">
            <input type="submit" class="btn btn-primary">
        </div>
       </form>
</main>
{% endblock %}